[#modes]
= Режимы

Режим определяет поведение {emacs} при работе с буфером.
В большинстве других редакторов список доступных команд и функций зависит от типа файла, с которым вы работаете.
В {emacs} немного другая система.

В каждом буфере активен один _основной режим_ (primary mode) и несколько _дополнительных_ (minor modes).

Основной режим определяет базовое поведение {emacs} при работе с буфером: подсветка синтаксиса, основные привязки клавиш, функции рефакторинга и так далее.

Только один режим может быть основным: при выборе другого основного режима предыдущий перестаёт действоватьfootnote:[Существуют пакеты, позволяющие активировать несколько основных режимов сразу.].

По области действия режимы делятся на локальные, действующие только в пределах активного буфера, и глобальные, действующие на все открытые буферы.

Некоторые пакеты предоставляют команды для активации соответствующих локального и глобального режима.
Например, в пакете `whitespace-mode.el` доступны команды `whitespace-mode` и `global-whitespace-mode`.


[#modes-list]
== Список

Названия некоторых активных режимов выводятся в строке статуса.

Чтобы получить более полный список действующих в буфере режимов, нажмите kbd:[C-h m].


[#modes-toggle]
== Включение / выключение

Чтобы включить основной режим, выполните соответствующую команду в минибуфере.
Выполнение команды включения основного режима _идемпотентно_ -- сколько бы раз вы не вызывали соответствующую команду, эффект будет иметь только самый первый вызов.

В то же время дополнительные режимы ведут себя иначе.
Выполнение соответствующей команды _переключает_ (toggle) состояние режима -- если он был включен, то он выключится, и наоборот.
