[#store-settings]
= Хранение настроек

При запуске GNU Emacs проверяет существование следующих файлов:

. `~/.emacs.el`;
. `~/.emacs.d/init.el`;
. `~/.config/emacs/init.el`.

Как только хотя бы один из этих файлов будет найден, поиск остановится, а GNU Emacs загрузит настройки.
Рассмотрим плюсы и минусы использования того или иного расположения конфигурационного файла.

* `~/.emacs.el`
+
--
Поскольку этот файл лежит в корне домашнего каталога, им не очень удобно управлять с помощью систем контроля версий.
Например, в Git для удобной работы вам нужно будет добавить в список игнорирования все остальные файлы и каталоги, хранящиеся в домашнем каталоге.
--
* `~/.emacs.d/init.el`
+
--
Удобное решение, поскольку управлять отдельным каталогом с помощью того же Git значительно проще, чем в случае с `~/.emacs.el`.
Официальная https://www.gnu.org/software/emacs/manual/html_node/emacs/Find-Init.html[документация GNU Emacs] предполагает, что вы используете для хранения конфигурации именно файл `~/.emacs.d/init.el`.
--
* `~/.config/emacs/init.el`
+
--
Этот способ будет работать только в том случае, когда определена переменная окружения `XDG_CONFIG_HOME`.

* Такой переменной по умолчанию нет в Microsoft Windows.
* Эта переменная может быть не определена в используемом окружении на базе pass:[*nix], например, при работе на сервере.
--

Далее считается, что ваш основной конфигурационный файл хранится по пути `~/.emacs.d/init.el`.
