[#glossary]
= Глоссарий

Поскольку у {emacs} нет локализации на русский язык, переводы приведённых здесь терминов сделаны весьма произвольно.

Buffer, буфер::
+
--
Буфер -- это интерфейс взаимодействия {emacs} с пользователем.

В буферах выводится содержимое файлов и журналов.
Через буферы выполняется ввод текста.

Буфер может быть связан с файлом, но может существовать и сам по себе.
В то же время файл _всегда_ открывается в буфере.
--

Frame, фрейм::
+
--
Фреймом называется окно операционной системы, в котором работает отдельный экземпляр (процесс) {emacs}.

Вы можете запустить один процесс {emacs} и создать несколько фреймов, либо запустить несколько экземпляров {emacs}, и у каждого из них будет свой фрейм.

Фреймы позволяют использовать возможности оболочки рабочего стола для удобного размещения окон {emacs}.

Фреймы одного и того же экземпляра {emacs} работают как единое целое и используют одни и те же ресурсы.
Это значит, что каждый фрейм «знает» о буферах и файлах, открытых в других фреймах.
Также у них общая область kill ring, история команд и так далее.
--

Minibufer, минибуфер::
+
--
Минибуфером называется особый буфер, используемый для ввода команд и вывода сообщений.
Он размещается в нижней части каждого _окна_ {emacs}.

По умолчанию переход в минибуфер выполняется с помощью сочетания клавиш kbd:[M-x].
--

Package, пакет::
+
--
Пакетом называется один или несколько файлов с кодом на языке Emacs Lisp.
Можно считать пакеты аналогом плагинов или расширений.
--

Window, окно::
+
--
Окно в {emacs} -- это видимая область, в которой выводится содержимое буфера.
Содержимое одного и того же буфера может выводиться в нескольких окнах одновременно.

[NOTE]
====
Не путайте окна операционной системы с окнами {emacs} -- это не одно и то же.
====
--
