[#index]
= Добро пожаловать!
:description: Добро пожаловать на сайт «GNU Emacs по-русски»!
:sectanchors:
:page-tags: emacs

Добро пожаловать на сайт, посвящённый свободному текстовому редактору GNU Emacs!


[#index-before-you-begin]
== Перед началом работы

Прежде чем начать работу с GNU Emacs, следует определиться с целями.

Итак, GNU Emacs будет вам полезен в следующих случаях:

* Вы много работаете с текстом.
+
--
Если вам приходится работать с большими объёмами текста, то удобный редактор -- именно то, что вам нужно.
Используемый инструмент должен _помогать_ вам в работе, а не заставлять бороться с ним.
В GNU Emacs есть множество функций, позволяющих эффективно работать с текстом: регистры, kill-ring, сниппеты, аббревиатуры и многое другое.
--
* Вам нужен текстовый редактор, не зависящий от воли отдельных людей или корпораций.
+
--
Здесь показательна судьба Atom.

Этот бесплатный редактор от разработчиков GitHub в своё время изменил многое.
Появился редактор, способный работать сразу на почти всех возможных платформах (ценой снижения быстродействия), легко расширяемый, с открытым кодом.

Однако, стоило Microsoft купить GitHub, и разработка редактора была свёрнута.
Все наработки перекочевали в Visual Studio Code.
Это хороший редактор, по возможностям не уступающим многим IDE.
Вместе с ним у нас появилась технология Language Server Protocol (LSP).

Не смотря на все плюсы, Visual Studio Code зависит от воли корпорации Microsoft.
Как и в случае с Atom, в любой момент поддержка и разработка редактора VS Code может быть свёрнута, и вы ничего не сможете с этим сделать.
--
* Вы хотите, чтобы ваши знания не обесценились.
+
--
Любой инструмент требует времени на обучение.
Досадно, когда часы и дни, потраченные на изучение инструмента, обесцениваются, потому что авторы бросают его поддержку.
Вам приходится повторять цикл обучения снова и снова…

Если вы используете GNU Emacs, то можете быть уверены, что в ближайшие годы он, скорее всего, продолжит развиваться.
--


[#index-pitfalls]
== Чего ждать не стоит

Если вы решили, что хотите научится пользоваться {emacs}, будьте готовы к сложностям.

* Вам может показаться, что {emacs} похож на другие редакторы.
+
--
Некоторые вещи в {emacs} работают так же, как и везде.
Например, вам не нужно переключение режимов, как в VIM, чтобы начать вводить текст.

Однако, привязки клавиш по умолчанию отличаются от того, к чему вы привыкли.

kbd:[Ctrl+C], kbd:[Ctrl+V] и многие другие сочетания работать *не будут*.
Что ещё хуже, многие сочетания будут работать вообще не так, как вы привыкли.
Например, kbd:[Ctrl+W] не закрывает открытый файл, а перемещает текст в особую область, называемую kill ring.

Это значит, что ваш опыт работы с другими редакторами не только вам не поможет, но даже будет мешать.
Придётся всему учиться с нуля.
--
* Нужно будет приложить усилия.
+
--
{emacs} не для лентяев.
Вам придётся выучить наизусть большое количество нового материала:

* термины;
* сочетания и последовательности клавиш;
* команды;
* режимы;
* основы языка программирования Emacs Lisp.
--
* Создание собственной конфигурации требует времени.
+
--
Будьте моральны готовы к тому, что все настройки нужно будет делать путём правок в конфигурационном файле.
У {emacs} есть псевдографический интерфейс `cusomize`, предоставляющий интерактивный режим для управления настройками, но использоваться он не будет.
--
