[#packages]
= Пакеты

Пакет::
+
--
Пакетом называется один или несколько файлов с кодом на языке Emacs Lisp, выполняющих определённую задачу.
--

Пакеты делятся на несколько типов.

* Встроенные (built-in) пакеты поставляются вместе с {emacs}.
* Сторонние пакеты могут быть установлены различными способами.
Кроме этого, некоторые пакеты время от времени берёт под крыло проект GNU, и они становятся встроенными при выходе очередной версии {emacs}.
Например, это случилось с `use-package.el` и `which-key.el`.

Сторонние пакеты могут быть установлены разными способами, но рекомендуемым является использование архивов пакетов.

[#archives]
== Архивы пакетов

Архивы пакетов позволяют использовать встроенный пакет `package.el` для управления пакетами.
Это избавляет вас от необходимости искать и скачивать исходный код пакетов из различных источников.
Достаточно настроить {emacs} на использование нужных архивов, и все нужные пакеты можно будет устанавливать из них.

GNU ELPA::
+
--
Этот архив пакетов управляется GNU.
Пакеты в нём не очень новые и редко обновляются, но все они тщательно протестированы и, как правило, снабжены подробной документацией.

Количество пакетов невелико, некоторые из них устарели морально.

Однако, при использовании пакетов из этого архива у вас вряд ли будут с ними какие-то проблемы.
--

MELPA::
+
--
Этот крупнейший архив пакетов управляется сообществом.
Каждый пакет в нём собирается на основе последнего коммита в репозиторий проекта.
Эта особенность имеет два последствия:

* с одной стороны, в MELPA всегда самые свежие версии пакетов;
* с другой стороны, эти пакеты не отличаются стабильностью, а часто попросту сломаны.

Используйте пакеты из этого архива с большой осторожностью.
--

NON-GNU ELPA::
+
--
Этот архив содержит пакеты, по какие-то причинам не попавшие в GNU ELPA, часто из-за проблем с лицензией или документацией.

Пакетов здесь немного, но они хорошо протестированы и стабильны.
--

MELPA STABLE::
+
--
Этот архив отличается от MELPA только тем, что пакеты в нём собираются из ревизий кода, отмеченных тегами.

Обычно теги ставят на стабильные релизы, однако, нередки случаи, когда пакеты из MELPA Stable содержат ошибки или попросту сломаны.
В совсем редких случаях пакет из MELPA может работать стабильнее чем его версия из MELPA STABLE.

Этот репозиторий рекомендуется использовать в том случае, когда нужного пакета нет в GNU ELPA или NON-GNU ELPA
--

За список архивов в {emacs} отвечает переменная `package-archives`.
Чтобы воспользоваться всеми перечисленными пакетами, добавьте в начало `init.el` такой код:

.Настройка архивов пакетов
[source, emacs-lisp]
----
(require 'package)
(customize-set-variable 'package-enable-at-startup nil "Prevent double loading of libraries")
(add-to-list 'package-arhives '("gnu" . "https://elpa.gnu.org/packages/"))
(add-to-list 'package-arhives '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'package-arhives '("melpa-stable" . "https://stable.melpa.org/packages/"))
(add-to-list 'package-arhives '("nongnu" . "https://elpa.nongnu.org/nongnu/"))
(package-initialize)

----


[#archives-priority]
=== Приоритеты архивов

По умолчанию {emacs} будет устанавливать самую свежую версию пакета, которую найдёт.
Это значит, что при использовании приведённого выше фрагмента кода пакеты будут ставиться в первую очередь из MELPA, то есть будут крайне нестабильны.
Однако, вы можете изменить приоритеты архивов, задав их в значении настройки `package-archive-priorities`.

.Настройка приоритетов архивов
[source, emacs-lisp]
----
(customize-set-variable
 'package-archive-priorities
 '(("gnu" . 40)
   ("nongnu" . 30)
   ("melpa-stable" . 20)
   ("melpa" . 10)))
----

В этом случае {emacs} будет искать пакеты в следующем порядке:

. GNU ELPA
. NON-GNU ELPA
. MELPA STABLE
. MELPA

В большинстве случаев этого будет достаточно для стабильной работы {emacs}.


[#package-el]
== `package.el`

Встроенный пакет `package.el` предоставляет для работы со сторонними пакетами интерактивный режим и неинтерактивные команды.

[#package-el-install]
=== Установка

Для установки пакета в неинтерактивном режиме выполните две команды:

. `package-refresh-contents` -- обновление локальной копии архива пакетов.
. `package-install` -- команда, которая принимает на вход название пакета.
Если пакет не установлен, `package.el` поищет его в архивах и установит.
