[#archives]
= Архивы пакетов

Архив пакетов -- это место, в котором хранится список пакетов, которые можно установить в {emacs}.

Самые известные архивы пакетов:

GNU::
+
--
Этот архив уже давно доступен по умолчанию.
Пакеты в нём очень высокого качества, т. к. проект GNU тщательно следит за этим.
Обновления пакетов в этом репозитории довольно редки, но можно быть уверенным, что ничего не сломается и будет работать именно так, как написано в документации.

[NOTE]
====
Однако, есть и исключения.
Например, пакет `guess-language` лучше устанавливать из MELPA, так как версия в архиве GNU содержит ошибки.
====

*Страница проекта:* https://elpa.gnu.org[]
--

NonGNU Elpa::
+
--
Пакеты довольно высокого качества, по каким-либо причинам не попавшие в репозиторий GNUfootnote:[Часто -- несовместимость лицензий, хотя иногда бывает и несоблюдение автором требований GNU.].
Сломанные пакеты сюда попадают редко, как правило всё работает именно так, как и ожидается.

*Страница проекта:* https://elpa.nongnu.org[]
--


MELPA::
+
--
На текущий момент самый большой архив пакетов.
Единственная проблема -- пакеты формируются на основе самой свежей ревизии кода в основной ветке репозитория.
Сломанные, заброшенные и попросту устаревшие пакеты здесь не редкость.
Установленные отсюда пакеты обновляются порой по нескольку раз в день.

[WARNING]
====
Используйте пакеты из MELPA с осторожностью.
====

*Страница проекта:* https://melpa.org[]
--


MELPA Stable::
+
--
Пусть слово «stable» не вводит вас в заблуждение -- оно в данном случае означает совсем не то, что вы думаете.
Вот цитата с сайта архива:

[quote]
____
Packages in MELPA are built directly from the latest package source code in the upstream repositories, but we also build and publish packages corresponding to the latest tagged code in those repositories, where version tags exist.
These packages are published in a separate package archive called MELPA Stable. Most users should prefer MELPA over MELPA Stable.
____

Недословный перевод: пакеты в архиве MELPA Stable формируются на основе ревизий кода, отмеченных тегами.
Иногда это означает, что код стабилизирован и протестирован, но не всегда.

По своему опыту скажу, что с пакетами из этого архива значительно меньше проблем, чем с пакетами из MELPA.

*Страница проекта:* https://stable.melpa.org[]
--

.Код настройки архивов
[source, lisp]
----
include::example$packages/base-settings.el[]
----


[#archives-priorities]
== Приоритеты архивов

По умолчанию все архивы в {emacs} имеют одинаковый приоритет.
В этом случае предпочтение отдаётся самой новой версии пакета.
Например, пусть пакет доступен в архивах GNU, MELPA Stable и Melpa и имеет следующие версии:

* GNU: 1.8.0
* MELPA Stable: 1.8.1
* MELPA: 20250921

`package.el` сравнит версии и определит, что самая новая -- в архиве MELPA.

Как было сказано выше, пакеты из этого архива не отличаются стабильностью.
Однако, {emacs} позволяет настроить порядок, в котором отдаётся предпочтение архивам, то есть их приоритет.

.Настройка приоритета архивов
[source, lisp]
----
include::example$packages/priorities.el[]
----


[#archives-contents]
== Обновление локальной копии

Архивы не будут работать до тех пор, пока {emacs} не загрузит файл со списком доступных пакетов на локальный компьютер.
Для этого можно использовать команду `packages-refresh-contents`, но лучше добавить необходимый код в `init.el`.

.Загрузка списка пакетов из архивов
[source, lisp]
----
include::example$packages/refresh-contents.el[]
----
