[#package.el]
= Использование `package.el`

Теперь, когда архивы и их приоритеты настроены, пришло время научиться работать с `package.el`.


[#package-operations-installation]
== Установка

Для установки пакета:

. Обновите список доступных пакетов с помощью команды `package-refresh-contents`.

. Выполните команду `package-install`.
+
--
В минибуфере будет выведено приглашение ко вводу названия пакета:

[source, text]
----
Install package:
----
--

. Введите название нужного пакета и нажмите kbd:[RET].
+
--
{emacs} подключится к нужному архиву, загрузит из него код пакета и распакует в каталог `~/.emacs.d/elpa/`.
При необходимости также будут загружены и установлены зависимости.
--


[#package-operations-delete]
== Удаление

[NOTE]
====
Некоторые пакеты нельзя удалить средствами {emacs}:

* встроенные пакеты;
* пакеты, установленные с помощью пакетного менеджера ОС;
* пакеты, от которых зависит хотя бы один другой пакет.
====

Для удаления пакета:

. Выполните команду `package-delete`.
+
--
В минибуфере будет выведено приглашение ко вводу названия пакета:

[source, text]
----
Delete package:
----
--

. Введите название ненужного пакета и нажмите kbd:[RET].

. Если удаляемый пакет является зависимостью другого пакета, {emacs} напишет его название.
В этом случае придётся сначала удалить зависимый пакет.


[#package-operations-upgrade]
== Обновление

Чтобы обновить установленные пакеты, выполните команду `package-upgrade-all`.
{emacs} проверит содержимое архивов, и если найдёт у вас пакеты, которые можно обновить, предложит это сделать.
Подтвердите выполнение операции и перезапустите {emacs}.

Часто нет необходимости перезапускать редактор.
Однако, _иногда_ без этого он начинает вести себя странно.
Например, выдаёт ошибки при вызове команд, которые точно работали в предыдущей версии пакета.

Семь бед -- один reset!
Точнее, перезапуск редактора.


[#package-operations-list-packages]
== Интерактивный режим

Пакет `package.el` позволяет управлять пакетами в интерактивном режиме.

Чтобы открыть список пакетов, выполните команду `package-list-packages`.

[TIP]
====
У команды `package-list-packages` есть псевдоним -- `list-packages`.
====

`package-list-packages` автоматически выполняет команду `package-refresh-contents`.
Понадобится некоторое время, чтобы загрузить из архивов новые версии списков доступных пакетов.
Во время этого процесса в строке статуса будет выводиться надпись "Loading...".

Когда список пакетов будет загружен, в буфере `pass:[*Packages*]` отобразится таблица с несколькими колонками:

* безымянная колонка, в которой будет выводиться маркер назначенного действия;
* *Package* -- название пакета;
* *Version* -- версия пакета;
* *Status* -- состояние пакета;
** `available` -- пакет доступен для установки;
** `installed` -- пакет уже установлен с помощью менеджера пакетов;
** `dependency` -- пакет установлен как зависимость другого пакета;
** `build-in` -- встроенный пакет;
** `external` -- пакет установлен с помощью сторонних средств, например, менеджера пакетов операционной системы;
** `incompat` -- пакет несовместим с используемой версией {emacs};
** `new` -- пакета раньшеfootnote:[Во время предыдущего выполнения `package-refresh-contents`.] не было, а теперь он появился;
* *Archive* -- архив, в котором находится указанная версия пакета;
* *Description* -- краткое описание пакета на английском языке.

Для работы со списком используйте указанные в таблице сочетания и последовательности:

.Действия над пакетами
[%header, %autowidth, stripes=even, cols="^1, 4, ^1"]
|===
^| Сочетание ^| Действие                                           ^| Метка

| kbd:[n]     | Перейти к следующему пакету                         | --
| kbd:[p]     | Перейти к предыдущему пакету                        | --
| kbd:[i]     | Отметить пакет как устанавливаемый                  | `I`
| kbd:[d]     | Отметить пакет как удаляемый                        | `D`
| kbd:[U]     | Отметить пакет как обновляемый                      | `U`
| kbd:[u]     | Снять метку, если она установлена                   | --
.^| kbd:[RET]
.^| Показать краткую информацию о пакете.
Информация выводится в отдельном окне.
Чтобы закрыть его, нажмите kbd:[C-x 1]                            .^| --
| kbd:[w]     | Открыть веб-страницу пакета в браузере              | --
| kbd:[/ /]   | Сброс фильтра пакетов                               | --
| kbd:[/ n]   | Фильтрация списка пакетов по названию               | --
| kbd:[/ d]   | Фильтрация списка пакетов по описанию               | --
| kbd:[/ N]   | Фильтрация списка пакетов по названию или описанию  | --
| kbd:[/ a]   | Фильтрация списка пакетов по названию архива        | --
| kbd:[/ k]   | Фильтрация списка пакетов по ключевым словам        | --
| kbd:[/ m]   | Фильтрация списка пакетов по наличию маркера        | --
| kbd:[/ s]   | Фильтрация списка пакетов по статусу                | --
| kbd:[/ u]   | Фильтрация списка пакетов по возможности обновления | --
| kbd:[/ v]   | Фильтрация списка пакетов по версиям                | --
| kbd:[q]     | Закрыть буфер `pass:[*Packages*]`                   | --
|===


[#package-operations-example]
== Пример работы со списком пакетов

Допустим, мы хотим установить несколько пакетов:

* `doom-themes`;
* `markdown-mode`;
* `nerd-icons`.

Мы можем пойти двумя путями:

* Обновить список доступных пакетов с помощью `package-refresh-contents`, а затем три раза вызвать `package-install`.
* Открыть список доступных пакетов с помощью `package-list-packages`, найти нужные пакеты, отметить их, а затем запустить установку.

Очевидно, что при массовой установке пакетов второй способ предпочтительнееfootnote:[Чуть позже разберёмся с автоматической установкой пакетов. Не торопите события.].

Давайте прямо сейчас установим несколько пакетов, используя второй способ:

. Выполните команду `package-list-packages` и дождитесь обновления списка доступных пакетов.

. Найдите строки с нужными пакетами.
+
[TIP]
====
Пакеты в буфере `pass:[*Packages*]` упорядочены по статусу и алфавиту, но также вы можете использовать для поиска фильтры.
Например, чтобы найти пакет `doom-themes`, нажмите kbd:[/ n doom RET].
Для сброса фильтра нажмите kbd:[/ /].
====

. Чтобы отметить пакет как устанавливаемый, переместите курсор к соответствующей строке и нажмите kbd:[i].
В первой колонке появится метка `I`.

. Отметьте все нужные пакеты.

. Для запуска выполнения назначенных операций нажмите kbd:[x].
+
--
В строке статуса будет выведен запрос на подтверждение:

[source, text]
----
Packages to install: 3 (nerd-icons-0.1.0 markdown-mode-2.6 doom-themes-2.3.0).  Proceed? (y or n)
----
--

. Нажмите kbd:[y].
+
--
{emacs} запустит установку пакетов.
Будет открыто новое окно, в котором отобразится ход компиляции кода пакетов.

Когда установка пакетов будет закончена, в строке статуса будет выведено сообщение:

[source, text]
----
Operation [ Install 3 ] finished
----
--

. Чтобы закрыть буфер `pass:[*Packages*]`, нажмите kbd:[q].
+
--
Перезапускать {emacs} нет необходимости -- все установленные пакеты готовы к работе.
Чтобы убедиться в этом, выполните команду `load-theme`, указав название темы `doom-molokai`.
--
