[#builtin]
= Встроенные пакеты

В этом разделе представлены описания встроенных пакетов.
Эти пакеты входят в состав {emacs} и доступны без установки.

[#upgrade]
== Обновление

Возможно, вы захотите обновить встроенные пакеты.
В этом случае делайте так:

. Выполните команду `eval-expression`, kbd:[C-:].

. Введите выражение:
+
[source, emacs-lisp]
----
(setopt package-install-upgrade-built-in t)
----

. Нажмите kbd:[RET].

. Выполните команду `list-packages`.
+
--
`package.el` покажет большое количество пакетов, которые можно обновить.
--

. Нажмите kbd:[U], чтобы выделить все пакеты, но *не* нажимайте kbd:[x].

. Отфильтруйте пакеты по статусу: kbd:[/ m].

. С помощью клавиши kbd:[u] снимите выделение со всех пакетов, кроме тех, которые нужно обновить.
+
--
Как понять, что пакет нужно обновить? Нужно ответить "Да" на два вопроса:

* Я знаю для чего нужен этот пакет?
* Это обновление действительно необходимо?

[IMPORTANT]
====
Без необходимости не обновляйте встроенные пакеты!
Тем более не обновляйте пакеты, если не знаете, для чего они нужны!
====
--

. Нажмите kbd:[x] и подтвердите выполнение операций.
